export type Exercise = {
  id: string;
  name: string;
  muscle_group: string;
  video_url?: string;
};

export const SEED_EXERCISES: Exercise[] = [
  { id: "1", name: "Barbell Back Squat", muscle_group: "Legs" },
  { id: "2", name: "Deadlift", muscle_group: "Back" },
  { id: "3", name: "Bench Press", muscle_group: "Chest" },
  { id: "4", name: "Overhead Press", muscle_group: "Shoulders" },
  { id: "5", name: "Pull-Up", muscle_group: "Back" },
  { id: "6", name: "Barbell Row", muscle_group: "Back" },
  { id: "7", name: "Romanian Deadlift", muscle_group: "Legs" },
  { id: "8", name: "Incline Dumbbell Press", muscle_group: "Chest" },
  { id: "9", name: "Dumbbell Shoulder Press", muscle_group: "Shoulders" },
  { id: "10", name: "Lat Pulldown", muscle_group: "Back" },
  { id: "11", name: "Leg Press", muscle_group: "Legs" },
  { id: "12", name: "Leg Curl", muscle_group: "Legs" },
  { id: "13", name: "Leg Extension", muscle_group: "Legs" },
  { id: "14", name: "Bicep Curl", muscle_group: "Arms" },
  { id: "15", name: "Tricep Dip", muscle_group: "Arms" },
  { id: "16", name: "Tricep Pushdown", muscle_group: "Arms" },
  { id: "17", name: "Lateral Raise", muscle_group: "Shoulders" },
  { id: "18", name: "Face Pull", muscle_group: "Shoulders" },
  { id: "19", name: "Plank", muscle_group: "Core" },
  { id: "20", name: "Hanging Leg Raise", muscle_group: "Core" },
  { id: "21", name: "Russian Twist", muscle_group: "Core" },
  { id: "22", name: "Cable Fly", muscle_group: "Chest" },
  { id: "23", name: "Push-Up", muscle_group: "Chest" },
  { id: "24", name: "Goblet Squat", muscle_group: "Legs" },
  { id: "25", name: "Bulgarian Split Squat", muscle_group: "Legs" },
  { id: "26", name: "Hip Thrust", muscle_group: "Glutes" },
  { id: "27", name: "Glute Bridge", muscle_group: "Glutes" },
  { id: "28", name: "Calf Raise", muscle_group: "Legs" },
  { id: "29", name: "Seated Row", muscle_group: "Back" },
  { id: "30", name: "Chest Supported Row", muscle_group: "Back" },
  { id: "31", name: "Arnold Press", muscle_group: "Shoulders" },
  { id: "32", name: "Hammer Curl", muscle_group: "Arms" },
  { id: "33", name: "Skull Crusher", muscle_group: "Arms" },
  { id: "34", name: "Lunge", muscle_group: "Legs" },
  { id: "35", name: "Step-Up", muscle_group: "Legs" },
  { id: "36", name: "Kettlebell Swing", muscle_group: "Full Body" },
  { id: "37", name: "Burpee", muscle_group: "Full Body" },
  { id: "38", name: "Mountain Climber", muscle_group: "Core" },
  { id: "39", name: "Dead Bug", muscle_group: "Core" },
  { id: "40", name: "Ab Wheel", muscle_group: "Core" },
  { id: "41", name: "Chest Press Machine", muscle_group: "Chest" },
  { id: "42", name: "Shoulder Press Machine", muscle_group: "Shoulders" },
  { id: "43", name: "Preacher Curl", muscle_group: "Arms" },
  { id: "44", name: "Cable Row", muscle_group: "Back" },
  { id: "45", name: "Inverted Row", muscle_group: "Back" },
  { id: "46", name: "Pistol Squat", muscle_group: "Legs" },
  { id: "47", name: "Nordic Curl", muscle_group: "Legs" },
  { id: "48", name: "Farmer Carry", muscle_group: "Full Body" },
  { id: "49", name: "Box Jump", muscle_group: "Legs" },
  { id: "50", name: "Battle Ropes", muscle_group: "Full Body" },
];
